M48
; DRILL file {KiCad 8.0.3} date 2024-07-15T22:15:22+1000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-07-15T22:15:22+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X182.9Y-83.11
X182.9Y-88.89
T2
X186.55Y-84.0
M30
