M48
; DRILL file {KiCad 8.0.3} date 2024-06-14T23:01:07+1000
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-06-14T23:01:07+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0390
%
G90
G05
T1
X1.3543Y0.3894
X1.3543Y0.1618
T2
X0.0811Y0.4803
X0.2811Y0.5203
X0.2811Y0.4403
M30
